In [1]:
import tensorflow as tf
import numpy as np

# Python 연산과 Numpy 연산 차이점

In [25]:
t = [1, 2, 3]

## 1. Python 연산

In [18]:
# numpy가 아니라 list라서 아래는 오류 난다.
t + 5

TypeError: can only concatenate list (not "int") to list

In [19]:
t * 5 # 파이썬의 * 연산은 반복된다

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

## 2.Numpy 연산

In [20]:
np.int32(t) + 5

array([6, 7, 8])

In [21]:
np.int32(t) * 5 

array([ 5, 10, 15])

### a. Numpy Array

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a + 3 # Broadcasting 지원

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
a[[2, 4, 1]] # index array

array([2, 4, 1])

### b. Slicing

In [31]:
a[:3]

array([0, 1, 2])

## 3. Fancy Indexing

In [32]:
b = a.reshape(2, 5)

In [33]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
b[-1, -1]  # fancy indexing  마지막 행, 마지막열

9

In [35]:
b[[1,0], -1]

array([9, 4])

In [36]:
b[:, -1]

array([4, 9])

In [37]:
b[:, [2, -1, 0]]

array([[2, 4, 0],
       [7, 9, 5]])

# TensorFlow 와 Numpy reshape 차이점

In [38]:
a= np.arange(11, 19).reshape(-1, 1, 1, 2)

In [40]:
# 앞에 -1을 넣은것은 전체 갯수를  차원으로 나눈것

In [41]:
a

array([[[[11, 12]]],


       [[[13, 14]]],


       [[[15, 16]]],


       [[[17, 18]]]])