# 01_Tensor
In this notebook, we will see how to create and manipulate torch Tensors.

In [1]:
from __future__ import print_function
import numpy as np
import torch 
torch.manual_seed(1)

## Tensor is a matrix!
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

- 0-D Tensor: scalar
- 1-D Tensor: vector
- 2-D Tensor: matrix
- 3-D Tensor: tensor
- 4-D Tensor: tensor...

Tensors can be created with the following function:<br />
`torch.tensor(data, dtype=None, device=None, requires_grad=False)`

- `data`: initial data for the tensor
- `dtype`: the desired data type of returned tensor
- `device`: the desired device of returned tensor
- `requires_grad`: if autograd should record operations on the returned tensor (later on)

In [2]:
scalar = torch.tensor(3) # scalar
vector = torch.tensor([3]) # vector
print(scalar, vector)

tensor(3) tensor([3])


In [3]:
print(scalar.size(), vector.size()) # scalar is 0-dimensional

torch.Size([]) torch.Size([1])


In [4]:
print(scalar.item()) # get the Python number from a scalar.

3


In [5]:
x = torch.tensor([[1,2],[3,4]]) # 2D Tensor
print(x)

tensor([[1, 2],
        [3, 4]])


In [6]:
y = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]) # 3D Tensor
print(y)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### torch.dtype
Below is a complete list of available torch.dtypes (data types) and their corresponding tensor types.
<img src="images/dtype.png" width="500">

In [7]:
y.dtype # infers data type from data

torch.int64

### torch.device

In [8]:
y.device

device(type='cpu')

In [9]:
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
device

device(type='cuda')

### torch.Size

In [10]:
print(y.size(), y.numel())

torch.Size([3, 3, 3]) 27


## A few other methods to create a Tensor
There are some other tensor-creation operations
<img src="images/creation_ops.png" width="700">

In [11]:
print(torch.ones(3,3), torch.zeros(3,3), torch.eye(3,3), torch.rand(3,3), torch.randn(3,3), sep='\n')

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[-0.6617, -0.0426, -1.3328],
        [ 0.5161,  0.7455, -0.0751],
        [-0.6919, -0.4043,  0.2222]])


In [12]:
print(torch.arange(0, 3, step=0.5)) # This is Vector, Not a Matrix, Don't Get Confused

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])


In [13]:
x = np.array([[5,6],[7,8]])
x_torch = torch.from_numpy(x) # Converting a NumPy arraty to a Torch tensor
x_numpy = x_torch.numpy() # Converting a Torch tensor to a NumPy array
print(x_torch, x_numpy, sep='\n')

tensor([[5, 6],
        [7, 8]], dtype=torch.int32)
[[5 6]
 [7 8]]


In [14]:
x = torch.tensor([5.5, 3])
print(x)

x = x.new_ones(5, 3)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.5773, -1.7637,  0.2264],
        [-0.2355,  0.3019, -0.2770],
        [ 0.4771, -0.1103,  0.2913],
        [ 0.5848,  0.2149, -0.4090],
        [-0.1663,  0.6696,  0.1177]])


## Slicing, Concatenating, and Masking Tensor
PyTorch supports NumPy-style tensor indexing.

In [15]:
x = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
print(x)

print(x[0:2,:])

print(x[0:3,0])

x[0,:] = torch.tensor([0,0,0])
print(x)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([1, 2, 3])
tensor([[0, 0, 0],
        [2, 2, 2],
        [3, 3, 3]])


In [16]:
split_x = torch.split(x, 1, dim=0) # Return Tuple of splited tesnors
print(split_x)

print(split_x[0].size())

(tensor([[0, 0, 0]]), tensor([[2, 2, 2]]), tensor([[3, 3, 3]]))
torch.Size([1, 3])


In [17]:
split_cat = torch.cat(split_x, dim=0) # concatentae Tensor
split_stack = torch.stack(split_x, dim=1) # concatenate Tensor with New dimenstion
print(split_cat, split_stack, sep='\n')

print(split_cat.size(), split_stack.size(), sep='\n')

tensor([[0, 0, 0],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[[0, 0, 0],
         [2, 2, 2],
         [3, 3, 3]]])
torch.Size([3, 3])
torch.Size([1, 3, 3])


In [18]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)

mask = torch.ByteTensor([[0,0,1],[0,1,0]])

out = torch.masked_select(x,mask) # Extracting Values with ByteType Index Tensor

print(x, mask, out, sep='\n')

tensor([[-0.3584,  0.6513, -1.0273],
        [-0.7286, -0.7209,  1.1115]])
tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)
tensor([-1.0273, -0.7209])


## Reshaping on Dimension of Tensor

In [19]:
x  = torch.zeros(2, 1, 2)
print(x)

tensor([[[0., 0.]],

        [[0., 0.]]])


In [20]:
y = x.view(2,2) # Reahspe Tensor with view funciton
print(y, y.size(), sep='\n')

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])


In [21]:
y = x.view(-1) # -1 is special "Don't Care" symbol 
print(y, y.size(), sep='\n')

tensor([0., 0., 0., 0.])
torch.Size([4])


In [22]:
y = x.view(-1,4)
print(y, y.size(), sep='\n')

tensor([[0., 0., 0., 0.]])
torch.Size([1, 4])


In [23]:
y = x.squeeze()  # remove dimension of 1 
print(y, y.size(), sep='\n')

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])


In [24]:
y.unsqueeze_(1)  # insert dimension of 1 / the methods with the tailing '_' are in-place functions
print(y, y.size(), sep='\n')

tensor([[[0., 0.]],

        [[0., 0.]]])
torch.Size([2, 1, 2])


## Tensor Operations

### Arthmetic Operations
PyTorch supports NumPy-style tensor operations

In [25]:
x1 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)
x2 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)
print(x1, x2, sep='\n')

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [26]:
print(x1 + x2 , x1.add(x2), torch.add(x1,x2), sep='\n')

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [27]:
print(x1 * x2, x1.mul(x2), torch.mul(x1,x2), sep='\n') # Element-wise multiplication

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [28]:
print(x1 % 2,  x1 / 2, sep='\n')

tensor([[1., 0., 1.],
        [0., 1., 0.]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])


In [29]:
print(x1 + 10, x1 * 10, sep='\n') # broadingcasting

tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])


### Other useful math operations

In [30]:
print(x1.pow(2), torch.pow(x1,2), x1**2, sep='\n') # elementwise Power operation

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [31]:
# element-wise square root / logarithm to the base e, 10, 2
print(x1.sqrt(), x1.log(), x1.log10(), x1.log2(), sep='\n')

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
tensor([[0.0000, 0.3010, 0.4771],
        [0.6021, 0.6990, 0.7782]])
tensor([[0.0000, 1.0000, 1.5850],
        [2.0000, 2.3219, 2.5850]])


In [32]:
# summation / maximum / minimum / mean / standard deviation / absolute value
print(x1.sum(), x1.max(), x1.min(), x1.mean(), x1.std(), x1.abs(), sep='\n')

tensor(21.)
tensor(6.)
tensor(1.)
tensor(3.5000)
tensor(1.8708)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
value_along_row, index_along_row = x1.max(dim=0) # Find maximum index in the Tensor
value_along_column, index_along_column = x1.max(dim=1)
print(value_along_row, index_along_row)
print(value_along_column, index_along_column)

tensor([4., 5., 6.]) tensor([1, 1, 1])
tensor([3., 6.]) tensor([2, 2])


### Matrix operations

In [34]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.randn(3,4)
x2 = torch.randn(4,5)

print(torch.mm(x1,x2), x1.mm(x2), sep='\n')

tensor([[-3.9867,  3.9807,  0.1730,  0.9068, -0.7302],
        [-0.3917, -0.0361, -0.2434,  0.0573,  1.5814],
        [-1.6090, -1.6922, -0.2638, -1.1935, -0.5969]])
tensor([[-3.9867,  3.9807,  0.1730,  0.9068, -0.7302],
        [-0.3917, -0.0361, -0.2434,  0.0573,  1.5814],
        [-1.6090, -1.6922, -0.2638, -1.1935, -0.5969]])


In [35]:
# torch.mv(mat1, vector) -> matrix vector multiplication

x = torch.randn(3,4)
v = torch.randn(4)

print(torch.mv(x,v), x.mv(v), sep='\n')

tensor([-0.6492,  0.7737, -2.6722])
tensor([-0.6492,  0.7737, -2.6722])


In [36]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.randn(10,3,4)
x2 = torch.randn(10,4,5)

print(torch.bmm(x1,x2).size())

torch.Size([10, 3, 5])


In [37]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.tensor([1,2,3,4])
x2 = torch.tensor([1,1,1,1])

print(torch.dot(x1, x2))

tensor(10)


In [38]:
# torch.t(matrix) -> transposed matrix

x1 = torch.randn(3,4)

print(x1, x1.t(), sep='\n')

tensor([[ 0.1169, -0.3601, -0.7640,  0.8946],
        [ 1.4945,  0.3295, -0.2958, -0.7592],
        [-0.4087, -0.1341,  0.8123,  2.0045]])
tensor([[ 0.1169,  1.4945, -0.4087],
        [-0.3601,  0.3295, -0.1341],
        [-0.7640, -0.2958,  0.8123],
        [ 0.8946, -0.7592,  2.0045]])


In [39]:
a = torch.Tensor([[8.79,  6.11, -9.15,  9.57, -3.49,  9.84],
                  [9.93,  6.91, -7.93,  1.64,  4.02,  0.15],
                  [9.83,  5.04,  4.86,  8.83,  9.80, -8.99],
                  [5.45, -0.27,  4.85,  0.74, 10.00, -6.02],
                  [3.16,  7.98,  3.01,  5.80,  4.27, -5.31]]).t()
print(a, a.size(), sep='\n')

tensor([[ 8.7900,  9.9300,  9.8300,  5.4500,  3.1600],
        [ 6.1100,  6.9100,  5.0400, -0.2700,  7.9800],
        [-9.1500, -7.9300,  4.8600,  4.8500,  3.0100],
        [ 9.5700,  1.6400,  8.8300,  0.7400,  5.8000],
        [-3.4900,  4.0200,  9.8000, 10.0000,  4.2700],
        [ 9.8400,  0.1500, -8.9900, -6.0200, -5.3100]])
torch.Size([6, 5])


In [40]:
u, s, v = torch.svd(a) # singular value decomposition
print(u, s, v, sep='\n')
print(u.size(), s.size(), v.size())

tensor([[-0.5911,  0.2632,  0.3554,  0.3143,  0.2299],
        [-0.3976,  0.2438, -0.2224, -0.7535, -0.3636],
        [-0.0335, -0.6003, -0.4508,  0.2334, -0.3055],
        [-0.4297,  0.2362, -0.6859,  0.3319,  0.1649],
        [-0.4697, -0.3509,  0.3874,  0.1587, -0.5183],
        [ 0.2934,  0.5763, -0.0209,  0.3791, -0.6526]])
tensor([27.4687, 22.6432,  8.5584,  5.9857,  2.0149])
tensor([[-0.2514,  0.8148, -0.2606,  0.3967, -0.2180],
        [-0.3968,  0.3587,  0.7008, -0.4507,  0.1402],
        [-0.6922, -0.2489, -0.2208,  0.2513,  0.5891],
        [-0.3662, -0.3686,  0.3859,  0.4342, -0.6265],
        [-0.4076, -0.0980, -0.4933, -0.6227, -0.4396]])
torch.Size([6, 5]) torch.Size([5]) torch.Size([5, 5])


In [41]:
# Returns the p-norm of (first argument - second argument)
print(torch.dist(a, torch.mm(torch.mm(u, torch.diag(s)), v.t())))

tensor(1.4596e-05)
