In [51]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [52]:
col_names=['s1','c1','s2','c2','s3','c3','s4','c4','s5','c5','class' ]

In [12]:
# df = pd.read_csv('../../data/poker-hand-training-true.data',1,',')
# data = [df]
poker_train=pd.read_table('../../data/poker-hand-training-true.data', sep=',', names=col_names)
poker_test=pd.read_table('../../data/poker-hand-testing.data', sep=',', names=col_names)

In [14]:
poker_train.head()

s1  c1  s2  c2  s3  c3  s4  c4  s5  c5  class
0   1  10   1  11   1  13   1  12   1   1      9
1   2  11   2  13   2  10   2  12   2   1      9
2   3  12   3  11   3  13   3  10   3   1      9
3   4  10   4  11   4   1   4  13   4  12      9
4   4   1   4  13   4  12   4  11   4  10      9

In [15]:
poker_train.shape

(25010, 11)

In [16]:
poker_test.shape

(1000000, 11)

In [62]:
x_data = np.loadtxt('../../data/poker-hand-training-true.data',skiprows=1,delimiter=',', dtype='int32')
x_tdata = np.loadtxt('../../data/poker-hand-testing.data',skiprows=1,delimiter=',', dtype='int32')

In [63]:
x_data

array([[ 2, 11,  2, ...,  2,  1,  9],
       [ 3, 12,  3, ...,  3,  1,  9],
       [ 4, 10,  4, ...,  4, 12,  9],
       ...,
       [ 2,  1,  2, ...,  4, 13,  1],
       [ 2, 12,  4, ...,  4,  9,  1],
       [ 1,  7,  3, ...,  3,  7,  1]])

In [64]:
x_tdata

array([[ 3, 12,  3, ...,  2,  5,  1],
       [ 1,  9,  4, ...,  3,  9,  1],
       [ 1,  4,  3, ...,  3,  6,  1],
       ...,
       [ 1, 11,  4, ...,  2,  7,  1],
       [ 3, 11,  1, ...,  2,  8,  1],
       [ 2,  5,  2, ...,  3,  3,  2]])

In [65]:
x_train = x_data[:, 0:-1]
y_train = x_data[:, -1]

In [66]:
x_test = x_tdata[:, 0:-1]
y_test = x_tdata[:, -1]

In [78]:
# 1. Classfication Model 생성

W = tf.get_variable('W4', shape=[10,10], initializer=tf.initializers.glorot_normal())
b = tf.Variable(tf.zeros([10]))

# Classfication Model 설정
ph_x = tf.placeholder(tf.float32, shape=[None, 10])
z = tf.matmul(ph_x, W) + b
hx = tf.nn.softmax(z)

In [84]:
# 2. Cost function 최소화

loss_i = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=z, labels=tf.stop_gradient(y_train))
loss = tf.reduce_mean(loss_i)

optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss=loss)

In [85]:
# 3. 학습을 통해 실행

with tf.Session() as sess:     
    sess.run(tf.global_variables_initializer())
    for i in range(10001):
        sess.run(train, feed_dict={ph_x: x_train})
        if i % 2000 == 0:
            print(i, sess.run(loss, {ph_x: x_train}))
            
            
    preds = sess.run(hx, {ph_x: x_test})
    preds_arg = np.argmax(preds, axis=1)  # 1: 수평, 0: 수직
    print('acc: ', np.mean(preds_arg == y_test))
    print(preds_arg)            

0 9.062801
2000 0.98597187
4000 0.9840787
6000 0.9832058
8000 0.982832
10000 0.9825701
acc:  0.5012085012085012
[0 0 0 ... 0 0 0]
