In [4]:
import numpy as np

X = np.array([[1,1,0,0,0],
             [0,1,0,0,0],
             [0,0,1,0,0],
             [0,0,0,1,0]])

In [6]:
X.ndim, X.shape
# row:문서, column: 단어, DTM

(2, (4, 5))

In [8]:
X[0], X[:,0]
# 문서들 간의 내적, 문서의 길이로 정규화 => cosine

(array([1, 1, 0, 0, 0]), array([1, 0, 0, 0]))

In [9]:
X[0], X[1]
# X[0].dot(X[1]) / (nodrm(X[0])* norm(X[1]))

(array([1, 1, 0, 0, 0]), array([0, 1, 0, 0, 0]))

In [10]:
X

array([[1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [11]:
X.T

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [14]:
X[0] | X.T[:,0], X.T[:,1], X.T[:,2], X.T[:,3]

(array([1, 1, 0, 0, 0], dtype=int32),
 array([0, 1, 0, 0, 0]),
 array([0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 0]))

In [16]:
_X= X.dot(X.T)

In [20]:
# _X / X  row 마다 norm, X.T column 마다 norm

In [21]:
np.linalg.norm(X, axis=1)  # 열이니까. axis가 1

array([1.41421356, 1.        , 1.        , 1.        ])

In [22]:
from math import sqrt
sqrt(1+1)

1.4142135623730951

In [23]:
np.linalg.norm(X, axis=1).shape

(4,)

In [25]:
length = np.linalg.norm(X, axis=1)

In [26]:
length * length.T

array([2., 1., 1., 1.])

In [27]:
length.shape, length.T.shape

((4,), (4,))

In [29]:
length, length.T.reshape(1,4)

(array([1.41421356, 1.        , 1.        , 1.        ]),
 array([[1.41421356, 1.        , 1.        , 1.        ]]))

In [30]:
length.shape, length.T.reshape(1,4).shape

((4,), (1, 4))

In [31]:
length.reshape(4,1) * length.T.reshape(1,4)

array([[2.        , 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ]])

In [32]:
_X / (length.reshape(4,1) * length.T.reshape(1,4))

array([[1.        , 0.70710678, 0.        , 0.        ],
       [0.70710678, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [33]:
C = np.array([[1,0,1,0,0,0],
              [0,1,0,0,0,0],
              [1,1,0,0,0,0],
              [1,0,0,1,1,0],
              [0,0,0,1,0,1]])

In [34]:
C

array([[1, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [36]:
import pandas as pd

V = ['ship','boat','ocean','wood','tree']
pd.DataFrame(C, index=V)

0  1  2  3  4  5
ship   1  0  1  0  0  0
boat   0  1  0  0  0  0
ocean  1  1  0  0  0  0
wood   1  0  0  1  1  0
tree   0  0  0  1  0  1

In [41]:
U, Sigma, V = np.linalg.svd(C, full_matrices=False)

In [42]:
U.shape, Sigma.shape, V.shape

((5, 5), (5,), (5, 6))

In [43]:
V

array([[ 7.48623048e-01,  2.79711603e-01,  2.03628802e-01,
         4.46563110e-01,  3.25095956e-01,  1.21467154e-01],
       [-2.86453991e-01, -5.28459139e-01, -1.85761186e-01,
         6.25520701e-01,  2.19879758e-01,  4.05640944e-01],
       [-2.79711603e-01,  7.48623048e-01, -4.46563110e-01,
         2.03628802e-01, -1.21467154e-01,  3.25095956e-01],
       [-4.16290741e-16,  1.06695915e-15,  5.77350269e-01,
         2.38203550e-16, -5.77350269e-01,  5.77350269e-01],
       [ 5.28459139e-01, -2.86453991e-01, -6.25520701e-01,
        -1.85761186e-01, -4.05640944e-01,  2.19879758e-01]])

In [44]:
pd.DataFrame(V)

0             1         2             3         4         5
0  7.486230e-01  2.797116e-01  0.203629  4.465631e-01  0.325096  0.121467
1 -2.864540e-01 -5.284591e-01 -0.185761  6.255207e-01  0.219880  0.405641
2 -2.797116e-01  7.486230e-01 -0.446563  2.036288e-01 -0.121467  0.325096
3 -4.162907e-16  1.066959e-15  0.577350  2.382035e-16 -0.577350  0.577350
4  5.284591e-01 -2.864540e-01 -0.625521 -1.857612e-01 -0.405641  0.219880

In [45]:
U.dot(Sigma)

array([0.23405067, 0.21342152, 0.92433811, 1.24138537, 2.73938551])

In [46]:
np.diag(Sigma).shape

(5, 5)

In [47]:
U.dot(np.diag(Sigma)).dot(V)

array([[ 1.00000000e+00,  2.86617590e-16,  1.00000000e+00,
        -2.95749937e-16,  1.37119440e-16, -3.70786990e-16],
       [-5.86398640e-17,  1.00000000e+00, -1.65566828e-16,
         1.60296310e-16,  7.95478077e-17, -4.81987944e-17],
       [ 1.00000000e+00,  1.00000000e+00, -5.92405227e-16,
        -5.78771864e-17,  1.73354839e-17, -1.45489216e-16],
       [ 1.00000000e+00,  6.76013507e-17, -1.33481791e-16,
         1.00000000e+00,  1.00000000e+00,  2.53599716e-16],
       [-3.27568563e-16, -5.43662480e-16, -4.85726293e-16,
         1.00000000e+00,  2.09105806e-16,  1.00000000e+00]])

In [73]:
pd.DataFrame(np.round(U.dot(np.diag(Sigma)).dot(V)),index=['ship','boat','ocean','wood','tree'])

0    1    2    3    4    5
ship   1.0  0.0  1.0 -0.0  0.0 -0.0
boat  -0.0  1.0 -0.0  0.0  0.0 -0.0
ocean  1.0  1.0 -0.0 -0.0  0.0 -0.0
wood   1.0  0.0 -0.0  1.0  1.0  0.0
tree  -0.0 -0.0 -0.0  1.0  0.0  1.0

In [50]:
pd.DataFrame(C)

0  1  2  3  4  5
0  1  0  1  0  0  0
1  0  1  0  0  0  0
2  1  1  0  0  0  0
3  1  0  0  1  1  0
4  0  0  0  1  0  1

In [51]:
np.diag(Sigma[:2]).shape

(2, 2)

In [52]:
U.shape

(5, 5)

In [54]:
U[:,:2].shape, V[:2].shape

((5, 2), (2, 6))

In [74]:
pd.DataFrame(np.round(U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2])),index=['ship','boat','ocean','wood','tree'])

0    1    2    3    4    5
ship   1.0  1.0  0.0  0.0  0.0 -0.0
boat   0.0  0.0  0.0 -0.0 -0.0 -0.0
ocean  1.0  1.0  0.0 -0.0  0.0 -0.0
wood   1.0  0.0  0.0  1.0  1.0  0.0
tree   0.0 -0.0 -0.0  1.0  0.0  0.0

In [75]:
pd.DataFrame(U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2]),index=['ship','boat','ocean','wood','tree']) # K 차원을 줄임으로써  1번 2번 문서가 가깝다

0         1         2         3         4         5
ship   0.848146  0.515902  0.281625  0.129860  0.205743 -0.075882
boat   0.360778  0.357508  0.155125 -0.205653 -0.025264 -0.180389
ocean  1.003270  0.718285  0.360778 -0.050529  0.155125 -0.205653
wood   0.978006  0.129860  0.205743  1.028534  0.617139  0.411396
tree   0.129860 -0.386042 -0.075882  0.898674  0.411396  0.487278

In [57]:
pd.DataFrame(U.dot(np.diag(Sigma)).dot(V))

0             1             2             3             4  \
0  1.000000e+00  2.866176e-16  1.000000e+00 -2.957499e-16  1.371194e-16   
1 -5.863986e-17  1.000000e+00 -1.655668e-16  1.602963e-16  7.954781e-17   
2  1.000000e+00  1.000000e+00 -5.924052e-16 -5.787719e-17  1.733548e-17   
3  1.000000e+00  6.760135e-17 -1.334818e-16  1.000000e+00  1.000000e+00   
4 -3.275686e-16 -5.436625e-16 -4.857263e-16  1.000000e+00  2.091058e-16   

              5  
0 -3.707870e-16  
1 -4.819879e-17  
2 -1.454892e-16  
3  2.535997e-16  
4  1.000000e+00

In [58]:
C

array([[1, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [61]:
C.T.dot(C)

array([[3, 1, 1, 1, 1, 0],
       [1, 2, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 2, 1, 1],
       [1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [64]:
Ct = C.T
print(Ct.dot(Ct.T) / (np.linalg.norm(Ct, axis=1).reshape(Ct.shape[0],1) * np.linalg.norm(Ct, axis=1).T.reshape(1, Ct.shape[0])))

[[1.         0.40824829 0.57735027 0.40824829 0.57735027 0.        ]
 [0.40824829 1.         0.         0.         0.         0.        ]
 [0.57735027 0.         1.         0.         0.         0.        ]
 [0.40824829 0.         0.         1.         0.70710678 0.70710678]
 [0.57735027 0.         0.         0.70710678 1.         0.        ]
 [0.         0.         0.         0.70710678 0.         1.        ]]


In [65]:
CC = U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2])
print(CC)

[[ 0.8481456   0.51590232  0.28162515  0.12986018  0.20574267 -0.07588249]
 [ 0.36077778  0.35750764  0.15512454 -0.20565325 -0.02526436 -0.18038889]
 [ 1.00327014  0.71828543  0.36077778 -0.05052871  0.15512454 -0.20565325]
 [ 0.97800578  0.12986018  0.20574267  1.0285345   0.61713858  0.41139591]
 [ 0.12986018 -0.38604214 -0.07588249  0.89867432  0.41139591  0.4872784 ]]


In [67]:
C.T.dot(C)

array([[3, 1, 1, 1, 1, 0],
       [1, 2, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 2, 1, 1],
       [1, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [87]:
CCt = CC.T

print(CCt.dot(CCt.T) / (np.linalg.norm(CCt, axis=1).reshape(CCt.shape[0],1) * np.linalg.norm(CCt, axis=1).T.reshape(1, CCt.shape[0])))

[[ 1.          0.78183738  0.9501362   0.47443204  0.74011848  0.11059579]
 [ 0.78183738  1.          0.93727576 -0.17791796  0.15937503 -0.53318971]
 [ 0.9501362   0.93727576  1.          0.17626898  0.49351152 -0.20484118]
 [ 0.47443204 -0.17791796  0.17626898  1.          0.94311169  0.92736214]
 [ 0.74011848  0.15937503  0.49351152  0.94311169  1.          0.75020516]
 [ 0.11059579 -0.53318971 -0.20484118  0.92736214  0.75020516  1.        ]]


In [71]:
# 각열은 잠재의미(클러스터)를 나타내고, 그때의 행(단어)은 해당 잠재의미에서의 중요도를 나타냄
pd.DataFrame(U[:,:2].dot(np.diag(Sigma[:2])), index=['ship','boat','ocean','wood','tree'])

0         1
ship   0.952252 -0.472215
boat   0.279712 -0.528459
ocean  1.028335 -0.814913
wood   1.520282  0.558946
tree   0.568030  1.031162

In [72]:
pd.DataFrame(U[:,:3].dot(np.diag(Sigma[:3])), index=['ship','boat','ocean','wood','tree'])

0         1         2
ship   0.952252 -0.472215 -0.726275
boat   0.279712 -0.528459  0.748623
ocean  1.028335 -0.814913  0.468911
wood   1.520282  0.558946 -0.197550
tree   0.568030  1.031162  0.528725

In [76]:
data = pd.DataFrame(U[:,:3].dot(np.diag(Sigma[:3])), index=['ship','boat','ocean','wood','tree'])

In [77]:
data.sort_values(by=[0], ascending=False)[0].to_dict()

{'wood': 1.5202821146385517,
 'ocean': 1.028334651451026,
 'ship': 0.952251849979759,
 'tree': 0.568030264658793,
 'boat': 0.2797116034996999}

In [79]:
cluster1 = data.sort_values(by=[1], ascending=False)
cluster1[cluster1[1] > 0][1].to_dict()

{'tree': 1.031161645026429, 'wood': 0.5589464674814445}

In [82]:
data = pd.DataFrame(np.diag(Sigma[:3]).dot(V[:3]))

In [83]:
data

0         1         2         3         4         5
0  1.618898  0.604877  0.440347  0.965693  0.703020  0.262673
1 -0.456717 -0.842566 -0.296174  0.997319  0.350572  0.646747
2 -0.356713  0.954712 -0.569498  0.259686 -0.154906  0.414592

In [84]:
clusterData = np.diag(Sigma[:3]).dot(V[:3])

In [86]:
CCt = clusterData.T

print(CCt.dot(CCt.T) / (np.linalg.norm(CCt, axis=1).reshape(CCt.shape[0],1) * np.linalg.norm(CCt, axis=1).T.reshape(1, CCt.shape[0])))

[[ 1.          0.42223483  0.78542247  0.41805317  0.75047307 -0.01291529]
 [ 0.42223483  1.         -0.02533697 -0.00414719 -0.01597348  0.00853927]
 [ 0.78542247 -0.02533697  1.         -0.01640023  0.47162423 -0.49365825]
 [ 0.41805317 -0.00414719 -0.01640023  1.          0.87394629  0.87763513]
 [ 0.75047307 -0.01597348  0.47162423  0.87394629  1.          0.53404114]
 [-0.01291529  0.00853927 -0.49365825  0.87763513  0.53404114  1.        ]]
