In [3]:
import numpy as np

C = np.array([[1,1,0,0,0,0,0],
              [0,0,1,1,1,0,0],
              [0,1,0,0,0,1,0],
              [0,0,1,0,0,0,1],
              [0,0,0,1,1,0,1],
              [1,0,1,0,1,1,1]])

In [4]:
C

array([[1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1]])

In [7]:
import pandas as pd

I = ['A','B','C','D','E','F']
pd.DataFrame(C, columns=['cute','kitty','eat','rice','cake','hamster','bread'], index=I)

cute  kitty  eat  rice  cake  hamster  bread
A     1      1    0     0     0        0      0
B     0      0    1     1     1        0      0
C     0      1    0     0     0        1      0
D     0      0    1     0     0        0      1
E     0      0    0     1     1        0      1
F     1      0    1     0     1        1      1

```
1. SVD => U, Sigma, Vt (M, N)/(N, M) N개의 문성와 M개의 단어
2. U.Sigma, U[:,:K].Sigma[:K] => Latent Sematic 차원에서 어느 문서가 중요한지
3. Sigma.Vt, Sigma[:K].Vt[:K,:] => Latent Sematic 차원에서 어느 단어가 중요한지
4. 2-> 각 문서가 어는 문서와 유사한지(on Latent Semantic Dimensions)
5. 3-> 각 단어 가 어는 문서와 유사한지(on Latent Semantic Dimensions)
```

In [8]:
U, Sigma, V = np.linalg.svd(C, full_matrices=False)

In [9]:
U.shape, Sigma.shape, V.shape

((6, 6), (6,), (6, 7))

In [10]:
np.diag(Sigma).shape

(6, 6)

In [13]:
Col =['cute','kitty','eat','rice','cake','hamster','bread']

pd.DataFrame(np.round(U.dot(np.diag(Sigma)).dot(V)),columns=Col, index=I)

cute  kitty  eat  rice  cake  hamster  bread
A   1.0    1.0  0.0  -0.0  -0.0     -0.0    0.0
B  -0.0    0.0  1.0   1.0   1.0      0.0    0.0
C  -0.0    1.0 -0.0   0.0  -0.0      1.0   -0.0
D  -0.0    0.0  1.0   0.0   0.0     -0.0    1.0
E  -0.0    0.0  0.0   1.0   1.0      0.0    1.0
F   1.0   -0.0  1.0  -0.0   1.0      1.0    1.0

In [14]:
np.diag(Sigma[:2]).shape

(2, 2)

In [15]:
U.shape

(6, 6)

In [16]:
U[:,:2].shape, V[:2].shape

((6, 2), (2, 7))

In [17]:
pd.DataFrame(np.round(U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2])),columns=Col, index=I)

cute  kitty  eat  rice  cake  hamster  bread
A   1.0    1.0  0.0  -0.0  -0.0      1.0    0.0
B   0.0   -0.0  1.0   1.0   1.0      0.0    1.0
C   1.0    1.0  0.0  -0.0  -0.0      1.0    0.0
D   0.0   -0.0  0.0   0.0   1.0      0.0    0.0
E   0.0   -0.0  1.0   1.0   1.0      0.0    1.0
F   1.0    1.0  1.0   0.0   1.0      1.0    1.0

In [18]:
pd.DataFrame(U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2]),columns=Col, index=I) 

cute     kitty       eat      rice      cake   hamster     bread
A  0.589715  0.675476  0.096266 -0.303633 -0.051656  0.589715  0.096266
B  0.044610 -0.303633  0.691663  0.646125  0.842552  0.044610  0.691663
C  0.589715  0.675476  0.096266 -0.303633 -0.051656  0.589715  0.096266
D  0.200321 -0.007790  0.490414  0.344348  0.548564  0.200321  0.490414
E  0.044610 -0.303633  0.691663  0.646125  0.842552  0.044610  0.691663
F  0.816352  0.503954  0.965017  0.392853  0.957228  0.816352  0.965017

In [19]:
pd.DataFrame(U.dot(np.diag(Sigma)).dot(V))

0             1             2             3             4  \
0  1.000000e+00  1.000000e+00  2.589093e-16 -5.026436e-17 -1.956608e-16   
1 -2.615345e-16  4.981863e-16  1.000000e+00  1.000000e+00  1.000000e+00   
2 -1.382397e-15  1.000000e+00 -6.544914e-16  6.746307e-16 -9.979993e-17   
3 -2.541553e-16  2.721308e-16  1.000000e+00  4.218548e-16  1.546724e-16   
4 -1.659528e-16  4.095335e-16  3.384808e-16  1.000000e+00  1.000000e+00   
5  1.000000e+00 -1.368360e-15  1.000000e+00 -2.687597e-16  1.000000e+00   

              5             6  
0 -1.269952e-16  2.586652e-16  
1  7.535571e-16  4.728302e-16  
2  1.000000e+00 -2.661574e-16  
3 -1.075396e-16  1.000000e+00  
4  2.801495e-16  1.000000e+00  
5  1.000000e+00  1.000000e+00

In [20]:
C

array([[1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1]])

In [21]:
C.T.dot(C)

array([[2, 1, 1, 0, 1, 1, 1],
       [1, 2, 0, 0, 0, 1, 0],
       [1, 0, 3, 1, 2, 1, 2],
       [0, 0, 1, 2, 2, 0, 1],
       [1, 0, 2, 2, 3, 1, 2],
       [1, 1, 1, 0, 1, 2, 1],
       [1, 0, 2, 1, 2, 1, 3]])

In [22]:
Ct = C.T
print(Ct.dot(Ct.T) / (np.linalg.norm(Ct, axis=1).reshape(Ct.shape[0],1) * np.linalg.norm(Ct, axis=1).T.reshape(1, Ct.shape[0])))

[[1.         0.5        0.40824829 0.         0.40824829 0.5
  0.40824829]
 [0.5        1.         0.         0.         0.         0.5
  0.        ]
 [0.40824829 0.         1.         0.40824829 0.66666667 0.40824829
  0.66666667]
 [0.         0.         0.40824829 1.         0.81649658 0.
  0.40824829]
 [0.40824829 0.         0.66666667 0.81649658 1.         0.40824829
  0.66666667]
 [0.5        0.5        0.40824829 0.         0.40824829 1.
  0.40824829]
 [0.40824829 0.         0.66666667 0.40824829 0.66666667 0.40824829
  1.        ]]


In [23]:
CC = U[:,:2].dot(np.diag(Sigma[:2])).dot(V[:2])
print(CC)

[[ 0.58971512  0.67547606  0.09626579 -0.30363284 -0.05165575  0.58971512
   0.09626579]
 [ 0.04461004 -0.30363284  0.69166313  0.64612533  0.84255179  0.04461004
   0.69166313]
 [ 0.58971512  0.67547606  0.09626579 -0.30363284 -0.05165575  0.58971512
   0.09626579]
 [ 0.20032134 -0.00778976  0.49041403  0.34434801  0.54856423  0.20032134
   0.49041403]
 [ 0.04461004 -0.30363284  0.69166313  0.64612533  0.84255179  0.04461004
   0.69166313]
 [ 0.81635189  0.50395418  0.96501749  0.39285293  0.95722773  0.81635189
   0.96501749]]


In [24]:
C.T.dot(C)

array([[2, 1, 1, 0, 1, 1, 1],
       [1, 2, 0, 0, 0, 1, 0],
       [1, 0, 3, 1, 2, 1, 2],
       [0, 0, 1, 2, 2, 0, 1],
       [1, 0, 2, 2, 3, 1, 2],
       [1, 1, 1, 0, 1, 2, 1],
       [1, 0, 2, 1, 2, 1, 3]])

In [25]:
CCt = CC.T

print(CCt.dot(CCt.T) / (np.linalg.norm(CCt, axis=1).reshape(CCt.shape[0],1) * np.linalg.norm(CCt, axis=1).T.reshape(1, CCt.shape[0])))

[[ 1.          0.85575466  0.61080519  0.06618906  0.46981441  1.
   0.61080519]
 [ 0.85575466  1.          0.11304632 -0.45960567 -0.05468082  0.85575466
   0.11304632]
 [ 0.61080519  0.11304632  1.          0.83047325  0.98592173  0.61080519
   1.        ]
 [ 0.06618906 -0.45960567  0.83047325  1.          0.91192597  0.06618906
   0.83047325]
 [ 0.46981441 -0.05468082  0.98592173  0.91192597  1.          0.46981441
   0.98592173]
 [ 1.          0.85575466  0.61080519  0.06618906  0.46981441  1.
   0.61080519]
 [ 0.61080519  0.11304632  1.          0.83047325  0.98592173  0.61080519
   1.        ]]


In [26]:
pd.DataFrame(U[:,:2].dot(np.diag(Sigma[:2])),index=I)

0         1
A  0.349553  1.069114
B  1.314749 -0.672143
C  0.349553  1.069114
D  0.980358 -0.140448
E  1.314749 -0.672143
F  2.049621  0.564819